name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GITHUB_USERNAME: ${{ secrets.GIT_USER_NAME }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Test
        uses: nuuuwan/python-repo-test@v1
